/* Webhook trigger test
 Adding changes 
 Trigger build 
  Testing logs */

pipeline{
	agent any
	stages{
		stage('Build'){
			steps{
				echo 'Building...'
			}
		}
		stage('Test'){
			steps{
				echo 'Testing...'
			}
		}
		stage('Deploy'){
			steps{
				echo 'Deploying...'
			}
		}
		stage('Success'){
			steps{
				echo 'Job sucess...'
			}
		}
	}
}
